"use client";

import Link from "next/link";
import { FileText, Megaphone, Users, Zap } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

function Stat({ title, value, subtitle, href }: { title: string; value: string | number; subtitle: string; href: string }) {
  return (
    <Link href={href}>
      <Card className="h-full">
        <CardHeader>
          <CardTitle>{title}</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-3xl font-black">{value}</p>
          <p className="mt-1 text-xs text-[var(--text-dim)]">{subtitle}</p>
        </CardContent>
      </Card>
    </Link>
  );
}

export default function DashboardPage() {
  const { data: stats, isLoading } = trpc.stats.dashboard.useQuery();
  const { data: campaigns } = trpc.campaign.list.useQuery();
  const { data: topCreators } = trpc.creator.topByEngagement.useQuery({ limit: 5 });

  return (
    <div className="space-y-5">
      <header className="page-head">
        <span className="page-kicker">Dashboard</span>
        <h1 className="page-title">Command Dashboard</h1>
        <p className="page-sub">A clean, rebuilt interface for campaigns, creators, matching and AI briefs.</p>
      </header>

      <section className="grid grid-cols-1 gap-3 md:grid-cols-3">
        <Stat
          title="Campaigns"
          value={isLoading ? "-" : stats?.totalCampaigns ?? 0}
          subtitle="active in database"
          href="/campaigns"
        />
        <Stat
          title="Creators"
          value={isLoading ? "-" : stats?.totalCreators ?? 0}
          subtitle="in creator pool"
          href="/creators"
        />
        <Stat
          title="Briefs"
          value={isLoading ? "-" : stats?.totalBriefsGenerated ?? 0}
          subtitle="generated by AI"
          href="/brief"
        />
      </section>

      <section className="grid grid-cols-1 gap-3 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Recent Campaigns</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            {!campaigns?.length ? (
              <p className="text-sm text-[var(--text-dim)]">No campaigns yet.</p>
            ) : (
              campaigns.slice(0, 5).map((c) => (
                <div key={c.id} className="flex items-center justify-between rounded-lg border border-[var(--line-soft)] bg-[var(--surface-2)] px-3 py-2">
                  <div>
                    <p className="text-sm font-semibold">{c.objective}</p>
                    <p className="text-xs text-[var(--text-dim)]">{c.brand} · {c.target_country}</p>
                  </div>
                  <Link href={`/match?campaignId=${c.id}`} className="btn-secondary">
                    <Zap className="h-4 w-4" /> Match
                  </Link>
                </div>
              ))
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Top Creators</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            {!topCreators?.length ? (
              <p className="text-sm text-[var(--text-dim)]">No creators yet.</p>
            ) : (
              topCreators.map((c) => (
                <div key={c.id} className="flex items-center justify-between rounded-lg border border-[var(--line-soft)] bg-[var(--surface-2)] px-3 py-2">
                  <div>
                    <p className="text-sm font-semibold">@{c.username}</p>
                    <p className="text-xs text-[var(--text-dim)]">{c.country} · {c.followers.toLocaleString()} followers</p>
                  </div>
                  <span className="badge badge-ok">{c.engagement_rate}% ER</span>
                </div>
              ))
            )}
          </CardContent>
        </Card>
      </section>

      <section className="flex flex-wrap gap-2">
        <Link href="/campaigns" className="btn-primary"><Megaphone className="h-4 w-4" /> New Campaign</Link>
        <Link href="/match" className="btn-secondary"><Zap className="h-4 w-4" /> Run Match</Link>
        <Link href="/brief" className="btn-secondary"><FileText className="h-4 w-4" /> Generate Brief</Link>
        <Link href="/creators" className="btn-secondary"><Users className="h-4 w-4" /> Browse Creators</Link>
      </section>
    </div>
  );
}
